Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('fsmc_lcd', src, depend = ['BSP_USING_FSMC_LCD'], CPPPATH = CPPPATH)

Return('group')
